name: flutter_minio
description: "A new Flutter project."
version: 0.0.1
homepage:

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  buffer: ^1.2.3
  convert: ^3.1.1
  crypto: ^3.0.3
  http: ^1.1.0
  intl: ">=0.19.0 <0.21.0"
  meta: ^1.12.0
  mime: ">=1.0.4 <3.0.0"
  path: ^1.8.0
  xml: ^6.4.2

dev_dependencies:
  html: ^0.15.4
  mostly_reasonable_lints: ^0.1.2
  test: ^1.25.5